In [115]:
import numpy as np
import matplotlib.pyplot as plt
from helpers import *
import data_preprocessing
import importlib
importlib.reload(data_preprocessing)
import cross_validation
import TEST
importlib.reload(TEST)
importlib.reload(cross_validation)
import implemented_functions
importlib.reload(implemented_functions)



<module 'implemented_functions' from '/Users/christophersoriano/Library/Mobile Documents/com~apple~CloudDocs/Mac/Epfl/Master/MA3/Machine Learning/ML_project1/project1/implemented_functions.py'>

In [23]:
np.random.seed(42)

In [24]:
#Load Data
x_train_raw, x_test_raw,y_train_raw, train_ids, test_ids = load_csv_data('dataset')

In [6]:
print(x_train_raw.shape)
print(x_test_raw.shape)


(328135, 321)
(109379, 321)


In [18]:
x_train_raw

array([[5.3000000e+01, 1.1000000e+01, 1.1162015e+07, ...,           nan,
                  nan, 2.0000000e+00],
       [3.3000000e+01, 1.2000000e+01, 1.2152015e+07, ...,           nan,
                  nan,           nan],
       [2.0000000e+01, 1.0000000e+01, 1.0202015e+07, ..., 1.0000000e+00,
        2.0000000e+00, 2.0000000e+00],
       ...,
       [3.9000000e+01, 1.0000000e+01, 1.0202015e+07, ..., 2.0000000e+00,
        2.0000000e+00, 2.0000000e+00],
       [3.3000000e+01, 1.2000000e+01, 1.2302015e+07, ...,           nan,
                  nan, 2.0000000e+00],
       [3.2000000e+01, 9.0000000e+00, 9.1220150e+06, ...,           nan,
                  nan, 2.0000000e+00]], shape=(328135, 321))

In [37]:
#Reformat y_train to have 0's instead of -1's
y_train_original = y_train_raw.copy()
y_train_raw[y_train_raw == -1] = 0

In [38]:
#replace NaN by a float to treat NaN as a categorical feature
#TODO: NAN'S :apagnan -10 or 0 --> SAME BETWEEN TRAIN AND TEST 
x_test_raw = np.nan_to_num(x_test_raw, nan = -10.0)
x_test_raw.shape
x_test_raw

array([[ 4.4000000e+01,  2.0000000e+00,  2.0820150e+06, ...,
         1.0000000e+00,  1.0000000e+00,  2.0000000e+00],
       [ 2.7000000e+01,  1.0000000e+00,  1.1920150e+06, ...,
        -1.0000000e+01, -1.0000000e+01,  2.0000000e+00],
       [ 3.5000000e+01,  5.0000000e+00,  5.2620150e+06, ...,
         1.0000000e+00,  1.0000000e+00,  2.0000000e+00],
       ...,
       [ 9.0000000e+00,  1.1000000e+01,  1.1272015e+07, ...,
         9.0000000e+00,  9.0000000e+00, -1.0000000e+01],
       [ 1.5000000e+01,  1.2000000e+01,  1.2122015e+07, ...,
         1.0000000e+00,  1.0000000e+00,  2.0000000e+00],
       [ 4.5000000e+01,  1.2000000e+01,  1.2282015e+07, ...,
        -1.0000000e+01, -1.0000000e+01,  2.0000000e+00]])

### One Hot Encode

In [45]:
data_annoted = data_preprocessing.read_annotated_csv('dataset/data_anotated.csv')

In [46]:
x_train, y_train, x_test = data_preprocessing.preprocess_data2(x_train_raw[:,:], y_train_raw[:], x_test_raw[:,:], data_annoted)


In [ ]:
x_test

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [ ]:
"""x_train_filtered = data_preprocessing.remove_useless(x_train_raw, data_annoted)
x_test_filtered = data_preprocessing.remove_useless(x_test_raw, data_annoted)"""

'x_train_filtered = data_preprocessing.remove_useless(x_train_raw, data_annoted)\nx_test_filtered = data_preprocessing.remove_useless(x_test_raw, data_annoted)'

In [ ]:
"""data_train = data_preprocessing.clean_data(x_train_filtered[:100000,:], data_annoted)
data_test = data_preprocessing.clean_data(x_test_filtered[:100000,:], data_annoted)"""

'data_train = data_preprocessing.clean_data(x_train_filtered[:100000,:], data_annoted)\ndata_test = data_preprocessing.clean_data(x_test_filtered[:100000,:], data_annoted)'

In [47]:
np.savetxt('x_train_preprocessed.csv', x_train, delimiter=',')
np.savetxt('y_train_preprocessed.csv', y_train, delimiter=',')
np.savetxt('x_test_preprocessed.csv', x_test, delimiter=',')

In [116]:
x_train = np.loadtxt('x_train_preprocessed.csv', delimiter=',')
x_test = np.loadtxt('x_test_preprocessed.csv', delimiter=',')
y_train = np.loadtxt('y_train_preprocessed.csv', delimiter=',')

In [110]:
x_train.shape

(288135, 202)

In [111]:
x_test.shape

(40000, 202)

In [107]:

initial_w = np.zeros(x_train.shape[1])
max_iters = 50

x_test = x_train[-40000:,:]
y_test = y_train[-40000:]
x_train = x_train[:-40000,:]
y_train = y_train[:-40000]


w_least_squares, loss_ls = implemented_functions.least_squares(y_train, x_train)
print(f"Least Squares: Loss = {loss_ls}")

best_mse_coef = 0
best_mse_loss = np.inf
best_mse_weights = None
for gamma in [0.01, 0.1, 0.5, 1]:
    w_sgd, loss_sgd = implemented_functions.mean_squared_error_sgd(y_train,  x_train, initial_w, max_iters, gamma)
    if loss_sgd[-1] < best_mse_loss:
        best_mse_loss = loss_sgd[-1]
        best_mse_coef = gamma
        best_mse_weights = w_sgd
    print(f"Mean Squared Error SGD (gamma={gamma}): Loss = {loss_sgd}")

best_log_lasso_coef = 0
best_log_lasso_loss = np.inf
best_log_lasso_weights = None
for gamma in [0.01, 0.1, 0.5]:
    for lambda_ in [0.1, 0.01]:
        w_log_lasso, loss_log_lasso = implemented_functions.reg_logistic_lasso_subgradient(y_train, x_train, lambda_, initial_w, max_iters, gamma)
        if loss_log_lasso < best_log_lasso_loss:
            best_log_lasso_loss = loss_log_lasso
            best_log_lasso_weights = w_log_lasso
        print(f"Regularized Lasso Logistic Regression (gamma={gamma}, lambda={lambda_}): Loss = {loss_log_lasso}")
        
best_ridge_coef = 0
best_ridge_loss = np.inf
best_ridge_weights = None
for ridge_coef in [0.001, 0.01, 0.1, 1, 10]:
    w_ridge, loss_ridge = implemented_functions.ridge_regression(y_train, x_train, ridge_coef)
    if loss_ridge < best_ridge_loss:
        best_ridge_loss = loss_ridge
        best_ridge_coef = ridge_coef
        best_ridge_weights = w_ridge
    print(f"Ridge Regression (alpha={ridge_coef}): Loss = {loss_ridge}")

best_log_gamma = 0
best_log_loss = np.inf
best_log_weights = None
for gamma in [0.01, 0.1, 0.5, 1]:
    w_logistic, loss_logistic = implemented_functions.logistic_regression(y_train, x_train, initial_w, max_iters, gamma)
    if loss_logistic < best_log_loss:
        best_log_loss = loss_logistic
        best_log_gamma = gamma
        best_log_weights = w_logistic
    print(f"Logistic Regression: Loss = {loss_logistic}")

best_log_reg_coef = 0
best_log_reg_loss = np.inf
best_log_reg_weights = None
for gamma in [0.01, 0.1]:
    for reg_coef in [0.001, 0.01, 0.1]:
        w_reg_logistic, loss_reg_logistic = implemented_functions.reg_logistic_regression(y_train, x_train, reg_coef, initial_w, max_iters, gamma)
        if loss_reg_logistic < best_log_reg_loss:
            best_log_reg_loss = loss_reg_logistic
            best_log_reg_coef = reg_coef
            best_log_reg_weights = w_reg_logistic
        print(f"Regularized Logistic Regression (alpha={reg_coef}, gamma={gamma}): Loss = {loss_reg_logistic}")



/Users/christophersoriano/Library/Mobile Documents/com~apple~CloudDocs/Mac/Epfl/Master/MA3/Machine Learning/ML_project1/project1/implemented_functions.py:140: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  w = np.linalg.lstsq(tx,y)[0]


Least Squares: Loss = 0.0332660697950054
Mean Squared Error SGD (gamma=0.01): Loss = [0.04412341437173547, 0.04412341437173547, 0.04412341437173547, 0.04412341437173547, 0.04412341437173547, 0.04412341437173547, 0.0749258961124294, 0.054024583237476595, 0.04480624930402055, 0.04293347013949835, 0.04099149109216073, 0.04099936986926757, 0.042989632041564814, 0.044101282974364206, 0.04402058585745735, 0.046572555850146406, 0.045108203458412585, 0.04407016446199036, 0.04497490727528111, 0.04509829944583116, 0.0444487991714604, 0.04468083061976731, 0.044184175379590754, 0.047599225181837714, 0.046456071460284645, 0.04411796906478281, 0.043951025769181244, 0.04497369517638807, 0.04364201950361575, 0.043832719700901, 0.04325802603117721, 0.044659856709434335, 0.043913089904173835, 0.04416968698738487, 0.044588666324743544, 0.04396520139722135, 0.044863963891160194, 0.04445744811067444, 0.05317428300556608, 0.04214131538943833, 0.09233016679175486, 0.06112889542469105, 0.0490558958588751, 0.0

In [114]:

import implemented_functions


def test_methods(x_test, y_test, w_sgd, w_least_squares, best_ridge_weights, best_log_weights, best_log_reg_weights, threshold=0.5):
    accuracy, y_pred = implemented_functions.compute_accuracy(y_test, x_test, w_sgd, "SGD", threshold)
    print(f"F1 score SGD is {implemented_functions.compute_f1_score(y_test, y_pred)}")
    accuracy, y_pred = implemented_functions.compute_accuracy(y_test, x_test, w_least_squares, "Least Squares", threshold)
    print(f"F1 score Least Squares is {implemented_functions.compute_f1_score(y_test, y_pred)}")
    accuracy, y_pred = implemented_functions.compute_accuracy(y_test, x_test, best_ridge_weights, "Ridge", threshold)
    print(f"F1 score Ridge is {implemented_functions.compute_f1_score(y_test, y_pred)}")
    accuracy, y_pred = implemented_functions.compute_accuracy(y_test, x_test, best_log_weights, "Logistic", threshold)
    print(f"F1 score Logistic is {implemented_functions.compute_f1_score(y_test, y_pred)}")
    accuracy, y_pred = implemented_functions.compute_accuracy(y_test, x_test, best_log_reg_weights, "Regularized Logistic", threshold)
    print(f"F1 score Regularized Logistic is {implemented_functions.compute_f1_score(y_test, y_pred)}")
    accuracy, y_pred = implemented_functions.compute_accuracy(y_test, x_test, best_log_lasso_weights, "Regularized Lasso", threshold)
    print(f"F1 score Regularized Lasso is {implemented_functions.compute_f1_score(y_test, y_pred)}")
    return y_pred

def test_thresholds(x_test, y_test, weights, method):
    for threshold in [0.7, 0.71, 0.72, 0.73, 0.75,0.76, 0.77, 0.8, 0.9]:
        accuracy, y_pred = implemented_functions.compute_accuracy(y_test, x_test, weights, method, threshold)
        print(f"-----{method}: F1 score {method} at threshold {threshold} is {implemented_functions.compute_f1_score(y_test, y_pred)}")

test_methods(x_test, y_test, w_sgd, w_least_squares, best_ridge_weights, best_log_weights, best_log_reg_weights, threshold=0.5)
test_methods(x_test, y_test, w_sgd, w_least_squares, best_ridge_weights, best_log_weights, best_log_reg_weights, threshold=0.3)
test_methods(x_test, y_test, w_sgd, w_least_squares, best_ridge_weights, best_log_weights, best_log_reg_weights, threshold=0.7)

test_thresholds(x_test, y_test, best_log_weights, "Logistic")
test_thresholds(x_test, y_test, best_ridge_weights, "Ridge")





Accuracy of SGD is 8.870000000000001%
F1 score SGD is 0.16294663359970607
Accuracy of Least Squares is 91.3925%
F1 score Least Squares is 0.10315186246418338
Accuracy of Ridge is 75.62%
F1 score Ridge is 0.3702699212191657
Accuracy of Logistic is 0.0%
F1 score Logistic is nan
Accuracy of Regularized Logistic is 0.0%
F1 score Regularized Logistic is nan
Accuracy of Regularized Lasso is 0.0%
F1 score Regularized Lasso is nan
Accuracy of SGD is 8.870000000000001%
F1 score SGD is 0.16294663359970607
Accuracy of Least Squares is 90.2775%
F1 score Least Squares is 0.36214531736919797
Accuracy of Ridge is 56.005%
F1 score Ridge is 0.2779419005416051
Accuracy of Logistic is 0.0%
F1 score Logistic is nan
Accuracy of Regularized Logistic is 0.0%
F1 score Regularized Logistic is nan
Accuracy of Regularized Lasso is 0.0%
F1 score Regularized Lasso is nan
Accuracy of SGD is 8.870000000000001%
F1 score SGD is 0.16294663359970607
Accuracy of Least Squares is 91.14%
F1 score Least Squares is 0.0028137

In [117]:
accuracy, y_pred = implemented_functions.compute_accuracy(y_test, x_test, best_ridge_weights, "Ridge", threshold=0.72, mode='submission')
y_pred

array([-1., -1., -1., ..., -1.,  1., -1.])

In [118]:
ids = [i for i in range(328135, 437513+1)]
import helpers
helpers.create_csv_submission(ids, y_pred, 'submission3.csv')

In [ ]:
best_ridge_weights.shape

(575,)

In [ ]:
x_train.shape

(8658, 575)

In [ ]:
x_test.shape

(50000, 561)