In [286]:
import numpy as np
import matplotlib.pyplot as plt
from helpers import *
import data_preprocessing
import importlib
importlib.reload(data_preprocessing)


<module 'data_preprocessing' from '/Users/mpecaut/ML_project1/project1/data_preprocessing.py'>

In [269]:
np.random.seed(42)

In [270]:
#Load Data
x_train_raw, x_test_raw,y_train, train_ids, test_ids = load_csv_data('/Users/mpecaut/Documents/EPFL/MASTER/MA3/ML/projects/project1/dataset')

In [271]:
print(x_train_raw.shape)
print(x_test_raw.shape)


(328135, 321)
(109379, 321)


In [272]:
#Reformat y_train to have 0's instead of -1's
y_train_original = y_train.copy()
y_train[y_train == -1] = 0

In [273]:
#replace NaN by a float to treat NaN as a categorical feature
x_test_raw = np.nan_to_num(x_test_raw, nan = -10.0)
x_test_raw.shape

(109379, 321)

In [274]:
#look at ratio of heart attack/no heart attack in y
print(len(y_train[y_train == 0]))
print(len(y_train[y_train==1]))
print(len(y_train))

299160
28975
328135


### One Hot Encode

In [ ]:
data_annoted = data_preprocessing.read_annotated_csv('/Users/mpecaut/Documents/EPFL/MASTER/MA3/ML/projects/project1/dataset/data_anotated.csv')

In [ ]:
x_train_filtered = data_preprocessing.remove_useless(x_train_raw, data_annoted)
x_test_filtered = data_preprocessing.remove_useless(x_test_raw, data_annoted)

In [ ]:
data_train = data_preprocessing.clean_data(x_train_filtered, data_annoted)
data_test = data_preprocessing.clean_data(x_test_filtered, data_annoted)

[[0. 0. 1. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 1. 0.]
 ...
 [0. 0. 1. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 1. 0.]]
-------------------------
[[ 1.  5. 88. ...  0.  0.  0.]
 [88. 88.  0. ...  1.  1.  1.]
 [ 0.  0. 88. ...  0.  0.  0.]
 ...
 [88.  1. 88. ...  0.  0.  0.]
 [88. 88.  0. ...  0.  0.  0.]
 [ 7.  7.  2. ...  0.  0.  0.]]
